// Generated by CoffeeScript 1.9.1
(function() {
  var ActionProperty, assert,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  assert = require('assert');

  ActionProperty = (function(superClass) {
    extend(ActionProperty, superClass);

    function ActionProperty() {
      return ActionProperty.__super__.constructor.apply(this, arguments);
    }

    ActionProperty.set({
      storm: 'action'
    });

    ActionProperty.prototype.kind = 'action';

    ActionProperty.prototype.exec = function() {
      throw new Error("undefined action");
    };

    ActionProperty.prototype.get = function() {
      return (require('tosource'))(this.exec);
    };

    return ActionProperty;

  })(require('../property'));

  module.exports = ActionProperty;

}).call(this);
