// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = {
    Model: require('./model'),
    Object: require('./object'),
    Property: require('./property'),
    Action: require('./property/action'),
    Computed: require('./property/computed'),
    Relationship: require('./property/relationship'),
    BelongsTo: require('./property/belongsTo'),
    HasMany: require('./property/hasMany'),
    Registry: require('./registry'),
    Class: require('./class'),
    Promise: require('promise')
  };

}).call(this);
